---
title: "DTI Analysis For Tracy and Kelsey"
author: "Daniel Callow"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readxl")
library("lsr")
library("PairedData")
library("ggplot2")
library("ggpubr")
library("standardize")
library(tidyverse)
library(knitr)
library(effects)
library(psych)
library(candisc)
library(extrafont)
```

```{r, include=FALSE}
rm(list=ls())
diffusion_data <- read_excel("C:/Users/ddcc2/Downloads/DTI_results.xlsx", sheet = "Sheet2")
require(ggplot2)
apatheme=theme_bw()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        text=element_text(family='Arial', size=18,color = "black"),
        legend.title=element_blank(),
        legend.position=c(.7,.8),
        axis.text = element_text(color="black"),
        axis.line.x = element_line(color='black'),
        axis.line.y = element_line(color='black'))
diffusion_data$Gender = factor(diffusion_data$Gender)

shapiro.test(diffusion_data$md_anat_bil)

old = subset(diffusion_data, category=="old")
young = subset(diffusion_data, category=="young")
female = subset(diffusion_data, Gender==1)
male = subset(diffusion_data, Gender==2)

young_male = subset(diffusion_data, category=="young" & Gender=="2")
young_female = subset(diffusion_data, category=="young" & Gender=="1")
old_male = subset(diffusion_data, category=="old" & Gender=="2")
old_female = subset(diffusion_data, category=="old" & Gender=="1")

```

```{r}

## mean diffusivity by age and gender (not sure which we are going with)

model4 = lm(diffusion_data$md_anat_bil~diffusion_data$Age+diffusion_data$Gender)
summary(model4)

model5 = lm(diffusion_data$md_ant_hipp~diffusion_data$Age+diffusion_data$Gender)
summary(model5)

model6 = lm(diffusion_data$md_post_hipp~diffusion_data$Age+diffusion_data$Gender)
summary(model6)

## mean diffusivity by age gender and volume (not sure which we are going with)

model4 = lm(diffusion_data$md_anat_bil~diffusion_data$Age+diffusion_data$Gender+diffusion_data$Vwhole)
summary(model4)

model5 = lm(diffusion_data$md_ant_hipp~diffusion_data$Age+diffusion_data$Gender+diffusion_data$Vant)
summary(model5)

model6 = lm(diffusion_data$md_post_hipp~diffusion_data$Age+diffusion_data$Gender+diffusion_data$Vpost)
summary(model6)


## source memory via age and sex 

model7 = lm(diffusion_data$SM_SCorrect_FCorrect_Percent_W1~diffusion_data$Age+diffusion_data$Gender)
summary(model7)

```
